name: viswals_flutter_interview_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  provider: ^6.1.2
  screenshot: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints:
    git: https://github.com/Saltitans/flutter_lints.git
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400

    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400

flutter_gen:
  integrations:
    flutter_svg: false

  assets:
    outputs:
      style: camel-case
      class_name: GenAssets

  fonts:
    outputs:
      class_name: GenFontFamily

  colors:
    enabled: false
